name: jokebloke
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - anywidget==0.9.21
      - appier==1.34.12
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - blis==1.3.3
      - cachetools==6.2.2
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpathlib==0.23.0
      - comm==0.2.3
      - confection==0.1.5
      - contourpy==1.3.3
      - cycler==0.12.1
      - cymem==2.0.13
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - en-core-web-sm==3.8.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.61.0
      - fqdn==1.5.1
      - google==3.0.0
      - google-api==0.1.12
      - google-auth==2.43.0
      - google-genai==1.54.0
      - gtts==2.5.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipyaudioworklet==0.6.0
      - ipydatawidgets==4.3.5
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - murmurhash==1.0.15
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nltk==3.9.2
      - numpy==2.3.5
      - overrides==7.7.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - preshed==3.0.12
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - psygnal==0.15.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygame==2.6.1
      - pygments==2.19.2
      - pyobjc==12.1
      - pyobjc-core==12.1
      - pyobjc-framework-accessibility==12.1
      - pyobjc-framework-accounts==12.1
      - pyobjc-framework-addressbook==12.1
      - pyobjc-framework-adservices==12.1
      - pyobjc-framework-adsupport==12.1
      - pyobjc-framework-applescriptkit==12.1
      - pyobjc-framework-applescriptobjc==12.1
      - pyobjc-framework-applicationservices==12.1
      - pyobjc-framework-apptrackingtransparency==12.1
      - pyobjc-framework-audiovideobridging==12.1
      - pyobjc-framework-authenticationservices==12.1
      - pyobjc-framework-automaticassessmentconfiguration==12.1
      - pyobjc-framework-automator==12.1
      - pyobjc-framework-avfoundation==12.1
      - pyobjc-framework-avkit==12.1
      - pyobjc-framework-avrouting==12.1
      - pyobjc-framework-backgroundassets==12.1
      - pyobjc-framework-browserenginekit==12.1
      - pyobjc-framework-businesschat==12.1
      - pyobjc-framework-calendarstore==12.1
      - pyobjc-framework-callkit==12.1
      - pyobjc-framework-carbon==12.1
      - pyobjc-framework-cfnetwork==12.1
      - pyobjc-framework-cinematic==12.1
      - pyobjc-framework-classkit==12.1
      - pyobjc-framework-cloudkit==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-collaboration==12.1
      - pyobjc-framework-colorsync==12.1
      - pyobjc-framework-contacts==12.1
      - pyobjc-framework-contactsui==12.1
      - pyobjc-framework-coreaudio==12.1
      - pyobjc-framework-coreaudiokit==12.1
      - pyobjc-framework-corebluetooth==12.1
      - pyobjc-framework-coredata==12.1
      - pyobjc-framework-corehaptics==12.1
      - pyobjc-framework-corelocation==12.1
      - pyobjc-framework-coremedia==12.1
      - pyobjc-framework-coremediaio==12.1
      - pyobjc-framework-coremidi==12.1
      - pyobjc-framework-coreml==12.1
      - pyobjc-framework-coremotion==12.1
      - pyobjc-framework-coreservices==12.1
      - pyobjc-framework-corespotlight==12.1
      - pyobjc-framework-coretext==12.1
      - pyobjc-framework-corewlan==12.1
      - pyobjc-framework-cryptotokenkit==12.1
      - pyobjc-framework-datadetection==12.1
      - pyobjc-framework-devicecheck==12.1
      - pyobjc-framework-devicediscoveryextension==12.1
      - pyobjc-framework-dictionaryservices==12.1
      - pyobjc-framework-discrecording==12.1
      - pyobjc-framework-discrecordingui==12.1
      - pyobjc-framework-diskarbitration==12.1
      - pyobjc-framework-dvdplayback==12.1
      - pyobjc-framework-eventkit==12.1
      - pyobjc-framework-exceptionhandling==12.1
      - pyobjc-framework-executionpolicy==12.1
      - pyobjc-framework-extensionkit==12.1
      - pyobjc-framework-externalaccessory==12.1
      - pyobjc-framework-fileprovider==12.1
      - pyobjc-framework-fileproviderui==12.1
      - pyobjc-framework-findersync==12.1
      - pyobjc-framework-fsevents==12.1
      - pyobjc-framework-fskit==12.1
      - pyobjc-framework-gamecenter==12.1
      - pyobjc-framework-gamecontroller==12.1
      - pyobjc-framework-gamekit==12.1
      - pyobjc-framework-gameplaykit==12.1
      - pyobjc-framework-healthkit==12.1
      - pyobjc-framework-imagecapturecore==12.1
      - pyobjc-framework-inputmethodkit==12.1
      - pyobjc-framework-installerplugins==12.1
      - pyobjc-framework-instantmessage==12.1
      - pyobjc-framework-intents==12.1
      - pyobjc-framework-intentsui==12.1
      - pyobjc-framework-iobluetooth==12.1
      - pyobjc-framework-iobluetoothui==12.1
      - pyobjc-framework-iosurface==12.1
      - pyobjc-framework-ituneslibrary==12.1
      - pyobjc-framework-kernelmanagement==12.1
      - pyobjc-framework-latentsemanticmapping==12.1
      - pyobjc-framework-launchservices==12.1
      - pyobjc-framework-libdispatch==12.1
      - pyobjc-framework-libxpc==12.1
      - pyobjc-framework-linkpresentation==12.1
      - pyobjc-framework-localauthentication==12.1
      - pyobjc-framework-localauthenticationembeddedui==12.1
      - pyobjc-framework-mailkit==12.1
      - pyobjc-framework-mapkit==12.1
      - pyobjc-framework-mediaaccessibility==12.1
      - pyobjc-framework-mediaextension==12.1
      - pyobjc-framework-medialibrary==12.1
      - pyobjc-framework-mediaplayer==12.1
      - pyobjc-framework-mediatoolbox==12.1
      - pyobjc-framework-metal==12.1
      - pyobjc-framework-metalfx==12.1
      - pyobjc-framework-metalkit==12.1
      - pyobjc-framework-metalperformanceshaders==12.1
      - pyobjc-framework-metalperformanceshadersgraph==12.1
      - pyobjc-framework-metrickit==12.1
      - pyobjc-framework-mlcompute==12.1
      - pyobjc-framework-modelio==12.1
      - pyobjc-framework-multipeerconnectivity==12.1
      - pyobjc-framework-naturallanguage==12.1
      - pyobjc-framework-netfs==12.1
      - pyobjc-framework-network==12.1
      - pyobjc-framework-networkextension==12.1
      - pyobjc-framework-notificationcenter==12.1
      - pyobjc-framework-opendirectory==12.1
      - pyobjc-framework-osakit==12.1
      - pyobjc-framework-oslog==12.1
      - pyobjc-framework-passkit==12.1
      - pyobjc-framework-pencilkit==12.1
      - pyobjc-framework-phase==12.1
      - pyobjc-framework-photos==12.1
      - pyobjc-framework-photosui==12.1
      - pyobjc-framework-preferencepanes==12.1
      - pyobjc-framework-pushkit==12.1
      - pyobjc-framework-quartz==12.1
      - pyobjc-framework-quicklookthumbnailing==12.1
      - pyobjc-framework-replaykit==12.1
      - pyobjc-framework-safariservices==12.1
      - pyobjc-framework-safetykit==12.1
      - pyobjc-framework-scenekit==12.1
      - pyobjc-framework-screencapturekit==12.1
      - pyobjc-framework-screensaver==12.1
      - pyobjc-framework-screentime==12.1
      - pyobjc-framework-scriptingbridge==12.1
      - pyobjc-framework-searchkit==12.1
      - pyobjc-framework-security==12.1
      - pyobjc-framework-securityfoundation==12.1
      - pyobjc-framework-securityinterface==12.1
      - pyobjc-framework-securityui==12.1
      - pyobjc-framework-sensitivecontentanalysis==12.1
      - pyobjc-framework-servicemanagement==12.1
      - pyobjc-framework-sharedwithyou==12.1
      - pyobjc-framework-sharedwithyoucore==12.1
      - pyobjc-framework-shazamkit==12.1
      - pyobjc-framework-social==12.1
      - pyobjc-framework-soundanalysis==12.1
      - pyobjc-framework-speech==12.1
      - pyobjc-framework-spritekit==12.1
      - pyobjc-framework-storekit==12.1
      - pyobjc-framework-symbols==12.1
      - pyobjc-framework-syncservices==12.1
      - pyobjc-framework-systemconfiguration==12.1
      - pyobjc-framework-systemextensions==12.1
      - pyobjc-framework-threadnetwork==12.1
      - pyobjc-framework-uniformtypeidentifiers==12.1
      - pyobjc-framework-usernotifications==12.1
      - pyobjc-framework-usernotificationsui==12.1
      - pyobjc-framework-videosubscriberaccount==12.1
      - pyobjc-framework-videotoolbox==12.1
      - pyobjc-framework-virtualization==12.1
      - pyobjc-framework-vision==12.1
      - pyobjc-framework-webkit==12.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pyttsx3==2.99
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - send2trash==1.8.3
      - six==1.17.0
      - smart-open==7.5.0
      - soupsieve==2.8
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - speechrecognition==3.14.4
      - srsly==2.5.2
      - stack-data==0.6.3
      - tenacity==9.1.2
      - terminado==0.18.1
      - thinc==8.3.10
      - tinycss2==1.4.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - traittypes==0.2.3
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - voila==0.5.11
      - wasabi==1.1.3
      - wcwidth==0.2.14
      - weasel==0.4.3
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
prefix: /opt/anaconda3/envs/jokebloke