name: jokebloke
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - annotated-types
      - anyio
      - argon2-cffi
      - arrow
      - asttokens
      - attrs
      - babel
      - beautifulsoup4
      - bleach
      - blis
      - cachetools
      - catalogue
      - certifi
      - cffi
      - charset-normalizer
      - click
      - cloudpathlib
      - colorama
      - comm
      - confection
      - contourpy
      - cycler
      - cymem
      - debugpy
      - decorator
      - defusedxml
      - executing
      - fastjsonschema
      - fonttools
      - fqdn
      - google-genai
      - gtts
      - h11
      - httpcore
      - httpx
      - idna
      - ipyaudioworklet
      - ipydatawidgets
      - ipykernel
      - ipython
      - ipython-pygments-lexers
      - ipywidgets
      - isoduration
      - jedi
      - jinja2
      - json5
      - jsonpointer
      - jsonschema
      - jupyter-client
      - jupyter-core
      - jupyter-events
      - jupyter-server
      - jupyter-server-terminals
      - jupyterlab-pygments
      - jupyterlab-server
      - jupyterlab-widgets
      - kiwisolver
      - langcodes
      - lark
      - markupsafe
      - matplotlib
      - matplotlib-inline
      - mistune
      - murmurhash
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - numpy
      - overrides
      - packaging
      - pandocfilters
      - parso
      - pexpect
      - pillow
      - platformdirs
      - preshed
      - prometheus-client
      - prompt-toolkit
      - psutil
      - pure-eval
      - pyasn1
      - pyasn1-modules
      - pycparser
      - pydantic
      - pygame
      - pygments
      - pyparsing
      - python-dateutil
      - python-json-logger
      - pyttsx3
      - pyyaml
      - pyzmq
      - referencing
      - requests
      - rfc3339-validator
      - rfc3986-validator
      - rpds-py
      - rsa
      - send2trash
      - six
      - smart-open
      - soupsieve
      - spacy
      - spacy-legacy
      - spacy-loggers
      - speechrecognition
      - srsly
      - stack-data
      - tenacity
      - terminado
      - thinc
      - tinycss2
      - tornado
      - tqdm
      - traitlets
      - traittypes
      - typer
      - typing-extensions
      - typing-inspection
      - tzdata
      - uri-template
      - urllib3
      - voila
      - wasabi
      - wcwidth
      - weasel
      - webcolors
      - webencodings
      - websocket-client
      - websockets
      - widgetsnbextension
      - wrapt
